const ErrorMessage = {
  INTERNAL_SERVER_ERROR : "INTERNAL_SERVER_ERROR",
  LIMIT_UNEXPECTED_FILE : "LIMIT_UNEXPECTED_FILE",
  LIMIT_FILE_SIZE : "LIMIT_FILE_SIZE",
  LIMIT_FILE_COUNT : "LIMIT_FILE_COUNT",
  LIMIT_FIELD_KEY : "LIMIT_FIELD_KEY",
}

Object.freeze(ErrorMessage);

export default ErrorMessage;